AWSTemplateFormatVersion: 2010-09-09
Description: enroll-ec2-mac credentials.
Parameters:
  JamfDomainNameOrIP:
    Type: String
    Description: The URL to your Jamf instance.
  JamfEnrollmentUser:
    Type: String
    Description: A Jamf user account with privileges to Create Computer Invitations.
  JamfEnrollmentUserPassword:
    Type: String
    NoEcho: True
    Description: The password for the Jamf account.
  LocalAdmin:
    Type: String
    Description: The local Mac administrator name (the default is ec2-user).
  LocalAdminPassword:
    Type: String
    NoEcho: True
    Description: The password for the local Mac administrator.
Resources:
  jamfSecret:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: Secret with credentials for enroll-ec2-mac.
      Type: SecureString
      
      Value: !Sub |
        {"jamfServerDomain": "${JamfDomainNameOrIP}","jamfEnrollmentUser": "${JamfEnrollmentUser}","jamfEnrollmentPassword": "${JamfEnrollmentUserPassword}","localAdmin": "${LocalAdmin}","localAdminPassword": "${LocalAdminPassword}"}
  MMSecretReadRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: MMReadSecrets
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'secretsmanager:GetResourcePolicy'
                  - 'secretsmanager:GetSecretValue'
                  - 'secretsmanager:DescribeSecret'
                  - 'secretsmanager:ListSecretVersionIds'
                  - 'secretsmanager:GetRandomPassword'
                  - 'secretsmanager:ListSecrets'
                Resource:
                  - !Ref jamfSecret
  MMInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref MMSecretReadRole
Outputs:
  MMJamfSecretID:
    Description: The ID of the created secret. Use with enroll-ec2-mac to enroll EC2 Mac instances.
    Value: !GetAtt jamfSecret.Name